version: "3.9"

services:
    
    postgres-db:
        image: postgres:12.0-alpine
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env.prod.db
        networks:
            - estate-react
    
    redis:
        image: redis:5-alpine
        networks:
            - estate-react
            
    api:
        build:
            context: .
            dockerfile: ./docker/prod/django/Dockerfile
        command: /home/app/web/start
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        expose:
            - "8000"
        env_file:
            - .env.prod
        depends_on:
            - postgres-db
            - redis
        networks:
            - estate-react
    
    celery_worker:
        build:
            context: .
            dockerfile: ./docker/prod/django/Dockerfile
        command: /home/app/web/start-celeryworker
        env_file:
            - .env.prod
        depends_on:
            - redis
            - postgres-db
        networks:
            - estate-react
    
    flower:
        build: 
            context: .
            dockerfile: ./docker/prod/django/Dockerfile
        command: /home/app/web/start-flower
        env_file:
            - .env.prod
        ports:
            - "5557:5555"
        depends_on:
            - redis
            - postgres-db
        networks:
            - estate-react


    nginx:
        restart: always
        depends_on:
            - api
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        build:
            context: ./docker/prod/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        networks:
            - estate-react


networks:
  estate-react:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
